[buildPlans.iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka.variants]
  inherits = "ss05"

    [buildPlans.iosevka.variants.design]
    j = "serifed"
    l = "serifed"

[buildPlans.iosevka.widths.condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.iosevka.widths.normal]
shape = 600
menu = 5
css = "normal"
