[buildPlans.iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka.variants]
inherits = "ss05"

[buildPlans.iosevka.variants.design]
capital-w = "straight-flat-top-serifless"
j = "flat-hook-serifed"
l = "serifed-asymmetric"
t = "flat-hook"
w = "straight-flat-top-serifless"
zero = "slashed"
three = "flat-top"
six = "open-contour"
nine = "open-contour"
